version: '3'
services:
  database:    
    volumes:
      - './docker/volumes/vipComemerce/testeWilliam/dev/var/lib/mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=1q2w3e4r
  api:
    volumes:
      - './:/api'
    environment:
      - NODE_ENV=development
      - DB_PASSWORD=1q2w3e4r
      - DB_USERNAME=root
      - EMAIL_USER=teste.vip.commerce@gmail.com
      - EMAIL_PASSWORD=1q2w3e4r@
