version: '3'
services:
  database:
    image: 'mysql:5'
    container_name: database
    ports:
      - '3306:3306'
  api:
    container_name: api
    build: ./
    ports:
      - '3000:3000'    
    depends_on:
      - database
    command: 'wait-for-it database:3306 -- npm start --prefix /api'
