version: '3'
services:
  database:    
    volumes:
      - './docker/volumes/vipComemrce/test/testeWilliam/var/lib/mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=1q2w3e4r
      - MYSQL_DATABASE=vipdb
  api:
    volumes:
      - './:/api'
    environment:
      - NODE_ENV=test
      - DB_PASSWORD=1q2w3e4r
      - DB_NAME=vipdb
      - DB_USERNAME=root
      - EMAIL_USER=teste.vip.commerce@gmail.com
      - EMAIL_PASSWORD=1q2w3e4r@
